#!/usr/bin/env bash
# Regenerate ansible/files/known_hosts from the current lab nodes.
#
#   bootstrap/ssh/scan-known-hosts.sh
#   make known-hosts
#
# hosts.yml is the single source of truth for hostnames and addresses (see its
# own header comment), so this resolves the cicd:cluster host list through
# Ansible's inventory rather than hardcoding IPs — the same reason
# bootstrap/cloud-init/render.sh shells out instead of re-deriving. `-c local`
# means no SSH connection is attempted just to read each host's own
# ansible_host; ssh-keyscan is the only thing that actually touches a node.
#
# Run this after reimaging a node (cloud-init generates fresh host keys on
# first boot) or when a node is added to hosts.yml. Always podman, not
# ENGINE-conditional like the Makefile's CONTAINER_RUN: this is a manual
# workstation step, never run by CI, same as render.sh.
#
# Trust-on-first-use: a scanned key is only as good as the network path it was
# scanned over. This diffs against what's already committed and prints
# anything that changed for you to verify out-of-band (the node's own console:
# `ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub`) before committing.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

OUT=ansible/files/known_hosts
ORG="${ORG:-nineteenseventytwo}"
IMAGE="${ANSIBLE_RUNNER:-ghcr.io/${ORG}/ansible-runner:$(cat images/ansible-runner/version.txt)}"

# ansible-runner's own Dockerfile bakes in ANSIBLE_FORCE_COLOR=1, which
# outranks ANSIBLE_NOCOLOR — so output carries ANSI escapes regardless of
# TTY. Strip them rather than fight ansible's color precedence.
strip_ansi() { sed -E $'s/\x1b\\[[0-9;]*m//g'; }

run_ansible() {
  if [[ "${RUNNER_LOCAL:-0}" == "1" ]] || command -v ansible >/dev/null 2>&1; then
    ANSIBLE_CONFIG=ansible/ansible.cfg ANSIBLE_VARS_ENABLED=host_group_vars ansible "$@" | strip_ansi
  else
    podman run --rm -i \
      -v "$PWD:/work" -w /work \
      -e ANSIBLE_CONFIG=/work/ansible/ansible.cfg \
      -e ANSIBLE_VARS_ENABLED=host_group_vars \
      "$IMAGE" ansible "$@" | strip_ansi
  fi
}

run_keyscan() {
  if command -v ssh-keyscan >/dev/null 2>&1; then
    ssh-keyscan "$@"
  else
    podman run --rm -i "$IMAGE" ssh-keyscan "$@"
  fi
}

echo "Resolving cicd:cluster hosts from ${OUT%/*}/../inventory/lab/hosts.yml..." >&2
PAIRS=$(run_ansible -i ansible/inventory/lab 'cicd:cluster' -c local \
  -m debug -a 'msg={{ inventory_hostname }},{{ ansible_host }}' \
  | awk -F': ' '/^ *msg:/ {print $2}')

if [[ -z "$PAIRS" ]]; then
  echo "error: no hosts resolved from cicd:cluster — check ansible/inventory/lab/hosts.yml" >&2
  exit 1
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "# Host keys for the lab nodes."
  echo "#"
  echo "# Generated by bootstrap/ssh/scan-known-hosts.sh from"
  echo "# ansible/inventory/lab/hosts.yml — do not hand-edit."
  echo "#"
  echo "# Ansible connects via ansible_host (the IP), so the IP is the name that"
  echo "# matters; the hostname is listed alongside for humans."
  echo "#"
  echo "# Last scanned: $(date -u +%Y-%m-%dT%H:%M:%SZ) from the workstation."
  echo "# Trust-on-first-use unless verified out-of-band against the node's own"
  echo "# console:  ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub"
  while IFS=, read -r NAME IP; do
    [[ -z "$NAME" ]] && continue
    echo "Scanning ${NAME} (${IP})..." >&2
    KEY=$(run_keyscan -t ed25519 -T 5 "$IP" 2>/dev/null | grep -v '^#') || true
    if [[ -z "$KEY" ]]; then
      echo "error: no ed25519 host key returned for ${NAME} (${IP}) — is it up?" >&2
      exit 1
    fi
    echo "${KEY/#${IP} /${NAME},${IP} }"
  done <<<"$PAIRS" | sort
} > "$TMP"

if [[ -f "$OUT" ]]; then
  echo >&2
  echo "=== diff against committed $OUT ===" >&2
  diff -u "$OUT" "$TMP" >&2 || true
fi

mv "$TMP" "$OUT"
trap - EXIT
echo >&2
echo "Wrote $OUT — review the diff above, verify anything new out-of-band, then commit." >&2
