---
apiVersion: v1
kind: Service
metadata:
  name: composer-service
  namespace: composer-dev
  labels:
    app: composer
    component: api
spec:
  selector:
    app: composer
    component: api
  ports:
    - port: 80
      targetPort: 8000
      name: http
