---
kubelet_node: false
longhorn_node: false

runner_host_ephemeral: true
runner_host_replicas: 2
runner_host_scope: "org"
runner_host_labels:
  - self-hosted
  - linux
  - arm64
  - lab-network

runner_host_mount_docker_socket: true
runner_host_user: "github-runner"

console_memory_guard_mb: 2048
