---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.1
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/cluster/ingress-nginx/values.yaml
    - repoURL: https://github.com/nineteenseventytwo/nineteenseventytwo-platform.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff: {duration: 30s, factor: 2, maxDuration: 10m}
