---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.12.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/cluster/longhorn/values.yaml
    - repoURL: https://github.com/nineteenseventytwo/nineteenseventytwo-platform.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff: {duration: 30s, factor: 2, maxDuration: 10m}
