---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.30.0
      helm:
        releaseName: vault
        valueFiles:
          - $values/cluster/vault/values.yaml
    - repoURL: https://github.com/nineteenseventytwo/nineteenseventytwo-platform.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff: {duration: 30s, factor: 2, maxDuration: 10m}
